feat: add .group_standards_iteration function
rformassspectrometry/MetaboAnnotation pull request #106
Opened 2023-10-03 13:54 UTC by philouail

New function referring to issue #105. 

This function iterates through the input matrix of compound m/z (with multiple adducts) and compounds names as row names. 

Compounds are grouped if their difference is superior to the `min_diff` input from the user. 

Users should be aware that because the function iterates through `x`, the compound at the bottom of the list is more complicated to group, and there's a possibility that some compounds will not be grouped with others. We advise increasing `nstd` and randomizing `x` to see if it can resolve this problem. 

I will also study a bit more on how to improve this function to prevent very small groups or compounds to be left alone, either by randomizing, or ordering the matrix in some way before starting the iteration. 

Other strategies of grouping (not iterating through a matrix) might also be developed.

lastly, if anyone as a better idea for the name I am fully open to suggestion !

2023-10-06 07:27 UTC, jorainer requested changes
Thanks Phili! Looks all good - except two very minor things related to white spaces. Please also fix that.

2023-10-06 07:27 UTC, jorainer commented on R/group_standards.R
> +      while(length(group) < max_nstd & i < nrow(x)) {
minor thing: can you please add a whitespace between `while` and `(`?

2023-10-06 07:27 UTC, jorainer commented on R/group_standards.R
> +    while(length(standard_groups) == 0 || any(lengths(standard_groups) <
please also here a whitespace after the `while`

2023-10-06 08:50 UTC, philouail commented
Minors fixes updated

2023-10-07 16:47 UTC, jorainer approved these changes
Thanks Phili!

2023-10-07 16:47 UTC, merged