matchMz updates
rformassspectrometry/MetaboAnnotation pull request #15
Opened 2021-05-27 10:25 UTC by andreavicini

2021-05-28 14:55 UTC, jorainer requested changes
Thanks @andreavicini ! I have some first suggestions and, after some testing, would also suggest to replace the `closest` with the `<=` approach. My reasons:

- we would no longer need to order `target` by m/z - which a) would be faster and b) helps avoiding potential problems with the different implementations for `numeric` or `data.frame`
- we don't need to calculate the difference again for the matching cases - should be a tiny little bit faster.

Please update the PR addressing (or discussing) the comments below. After that I would then also check the unit tests and documentation (which I did not do yet).

Thanks!

2021-05-28 14:55 UTC, jorainer commented on R/matchMz.R
> +         contains = "Param",
Most of the `*Param` classes have actually the same slot names and also duplicate their validity checks. I think it would be better to let the param object inherit from each other:

`MzParam` contains `"Param"`, `MzRtParam` contains `"MzParam"` (and hence you have only to define the additional slots not present in `MzParam`), `TargetMass2MzParam` contains `MzParam` and `TargetMass2MzRtParam` contains `TargetMass2MzParam` (well, then you would still need to add the `toleranceRt` slot - but not the `adducts` slot - I would not do a double inheritance).

2021-05-28 14:55 UTC, jorainer commented on R/matchMz.R
> +          })
I think you need to add also a line with `res` in order to return that from the function:

```
res@target <- target
res
```

2021-05-28 14:55 UTC, jorainer commented on R/matchMz.R
> +            res@query <- query
Same here I believe.

2021-05-28 14:55 UTC, jorainer commented on R/matchMz.R
> +              res@target <- target
In line 353 above you're ordering the `numeric` target within the `matchMz,numeric,numeric`. Wouldn't you also need to re-order `target` here?

2021-05-28 14:55 UTC, jorainer commented on R/matchMz.R
> +                 score = abs(queryMz - target$mz[cls]))
is you calculated the `diffs` above you could do here simple `score = diffs[cls]` instead.

2021-05-28 14:55 UTC, jorainer commented on R/matchMz.R
> +                 score = abs(queryMz - target$mz[cls]))
Same here - you can use `score = diffs[cls]`

2021-06-03 10:19 UTC, andreavicini commented on R/matchMz.R
> +              res@target <- target
I don't understand why. I thought  `target` had to be returned as it is. The ordering of `target` within `matchMz,numeric,numeric` is required only for `closest` to work but `matchMz,numeric,numeric` should return the matches referred to the original `target` order. Isn't that so?

2021-06-04 07:38 UTC, jorainer commented on R/matchMz.R
> +              res@target <- target
Hm, yes, but actually, now after removing the `closest` there is no need to order-reorder anymore.

2021-06-04 08:01 UTC, jorainer approved these changes
Excellent @andreavicini ! I will merge and check the unit tests (eventually add more - just to be on the save side) and also add some examples to the vignette.

Thanks, really a great PR!

2021-06-04 08:01 UTC, merged