matchMz between SummarizedExperiment and data.frame
rformassspectrometry/MetaboAnnotation pull request #21
Opened 2021-06-29 11:03 UTC by andreavicini

2021-06-30 13:42 UTC, jorainer requested changes
Very nice @andreavicini ! I have some small comments and actually maybe also a solution that helps you avoiding to re-implement every `matchMz` method again.

2021-06-30 13:42 UTC, jorainer commented on R/Matched.R
> +        if (missing(j)) j <- seq_len(dim(x)[2])
is that really required? I guess so, otherwise you would not have added it, but it surprises me.

2021-06-30 13:42 UTC, jorainer commented on R/Matched.R
> +    if(is.matrix(x) && is.null(colnames(x)))
Is `is.matrix` here really better? with `ndim == 2` we would also have supported `data.frame` and `DataFrame` (or any other two-dimensional data).

2021-06-30 13:42 UTC, jorainer commented on R/MatchedSummarizedExperiment.R
> +#' [matchSummarizedExperiment()] function will return this type of object.
I think you mean here `[matchMz()]` and not `[matchSummarizedExperiment()]`?

2021-06-30 13:42 UTC, jorainer commented on R/matchMz.R
> +            if (!mzColumn %in% colnames(rD_query))
could you not call then directly `matchMz(rd_query, target, param)` instead of needing to call all the code below?

2021-06-30 13:42 UTC, jorainer commented on R/MatchedSummarizedExperiment.R
> +  if(!is(object@target, "data.frame"))
do we really want to restrict us here to a `data.frame`? I would maybe support also `list`, `List`, `DataFrame` etc.

2021-06-30 13:42 UTC, jorainer commented on R/matchMz.R
> +#' ## Should I add here an example where `query` is a `SummarizedExperiment`?
no, in case we could add that to the vignette.

2021-06-30 13:42 UTC, jorainer commented on R/matchMz.R
> +            if (!mzColumn %in% colnames(rD_query))
Also, I'm wondering if it would not be possible to have a

```r
setMethod("matchMz", signature = c(query = "SummarizedExperiment", target = "ANY", param = "Param"), ...
```

that then *simply* extracts the `rowData` and then calls `matchMz` with that passing both `target` and `param` along. That way the correct downstream method (for `DataFrame` and the other parameters) should be called and you don't need to re-implement the code. You should then also be able to extract the `matched` data.frame from the result and create the `MatchedSummarizedExperiment` from that.

2021-06-30 20:57 UTC, andreavicini commented on R/MatchedSummarizedExperiment.R
> +#' [matchSummarizedExperiment()] function will return this type of object.
Yes, thank you!

2021-06-30 20:57 UTC, andreavicini commented on R/MatchedSummarizedExperiment.R
> +  if(!is(object@target, "data.frame"))
I wasn't sure about this. Ok, I'll remove the condition

2021-06-30 20:57 UTC, andreavicini commented on R/matchMz.R
> +            if (!mzColumn %in% colnames(rD_query))
It seems a great idea! Thank you!

2021-07-01 07:24 UTC, jorainer commented on R/Matched.R
> +        if (missing(j)) j <- seq_len(dim(x)[2])
OK, then it means that this is needed because of the way `[` is implemented for `SummarizedExperiment`.

2021-07-01 07:26 UTC, jorainer commented on R/Matched.R
> +    if(is.matrix(x) && is.null(colnames(x)))
I understand. Maybe not the cleanest solution, but then maybe something like

```r
if (ndim == 2 && !inherits(x, "SummarizedExperiment") && is.null(colnames(x)))
```

would work?

2021-07-20 12:21 UTC, jorainer approved these changes
Looks good to me @andreavicini ! I did not check the unit tests but I guess you added some testing all functionality. There is still the problem with the sorted/unsorted `@matches`, but I would open an issue describing that and add these fixes then as a separate PR (much easier to discuss/check smaller PR).

2021-07-20 12:28 UTC, merged