New versions of .dollar and .matchedData
rformassspectrometry/MetaboAnnotation pull request #24
Opened 2021-07-20 14:50 UTC by andreavicini

2021-07-21 09:37 UTC, jorainer requested changes
Looks really great @andreavicini . Some minor changes and notes. In addition:

- please run `devtools::document()` to update the documentation.
- please run `rcmdcheck::rcmdcheck(args = "--no-manual")` locally to ensure you have no errors/warnings before pushing (then the github checks should also be OK/green).

2021-07-21 09:37 UTC, jorainer commented on R/Matched.R
> +  if(name %in% .colnames(query, target, matches))
maybe it would make sense to have then also an `else stop("'", name, "' not available")` or something like this.

2021-07-21 09:37 UTC, jorainer commented on R/Matched.R
> +    ord <- order(idxs_qry) # Needed only if we want the entries of the returned vector
The definition is that `$` and `matchedData` always returns values in the same order than `query`. I would keep it like that, otherwise it would be confusing to the user.

2021-07-21 09:37 UTC, jorainer commented on R/Matched.R
> +    if (name == "target" || length(grep("^target_", name))){
please add a whitespace ` ` before the `{`.

2021-07-21 09:37 UTC, jorainer commented on tests/testthat/test_Matched.R
> +    #mo2@matches$score <- mo2@matches$score[c(4L, 4L, 5L, 1L, 2L)]
agree, you can remove this line. Since results are returned in the order of query we should not reorder the score.

2021-07-22 05:05 UTC, andreavicini commented on R/Matched.R
> +  if(name %in% .colnames(query, target, matches))
Ok, I will add it. I didn't because if I remember correctly when $ is called (for example on a data.frame) with a name that doesn't exist it just returns NULL

2021-07-22 09:31 UTC, jorainer commented on R/Matched.R
> +  if(name %in% .colnames(query, target, matches))
OK, I see. But for the `Matchedxxx` objects I would prefer to throw an error in such a case.

2021-07-23 11:16 UTC, andreavicini commented
Hello @jorainer, in addition to the changes you proposed I noticed that MatchedSpectra.R wasn’t updated with the fix on the ordering  so I thought to update that one as well. At first I simply correct the functions with the new approach (which I left but commented out in case we decided to keep those) but then I realized I could use the `.dollar` and `.matchedData` functions there as well ( I assumed that `spectraVariables(ms)` is equal to `.colnames(spectraData(ms@query), spectraData(ms@target), ms@matches)` as it seems to me but I could also modify the `.dollar`/`.matchedData` so that they can take as a parameter the available names/columns and call the proper function to find them outside)

2021-07-23 11:53 UTC, jorainer approved these changes
Excellent! Thanks @andreavicini ! And thanks for also fixing/updating the `MatchedSpectra`!

2021-07-23 11:53 UTC, merged