calculation of m/z error in ppm
rformassspectrometry/MetaboAnnotation pull request #59
Opened 2022-01-31 10:34 UTC by andreavicini

2022-01-31 14:20 UTC, jorainer requested changes
Thanks Andrea! Looks good to me. I would maybe just rename the variable.

2022-01-31 14:20 UTC, jorainer commented on R/matchMz.R
> +#' object contains the `ppm` variable with their m/z error in ppm (in addition
would maybe change that to:

contains the m/z error in ppm (variable `"ppm_error"`) as well as the absolute difference between the target and query m/z (variable `"score"`).

2022-01-31 14:20 UTC, jorainer commented on R/matchMz.R
> +                 ppm = diffs[cls] / target[cls, "mz"] * 10^6)
maybe better to call that column `ppm_error`? Then it would be clear what exactly it contains.

2022-01-31 16:12 UTC, andreavicini commented on R/matchMz.R
> +#' object contains the `ppm` variable with their m/z error in ppm (in addition
much better. Thanks!

2022-01-31 16:12 UTC, andreavicini commented on R/matchMz.R
> +                 ppm = diffs[cls] / target[cls, "mz"] * 10^6)
Yes, I agree. I thought that too but I saw `ppm` on your message and that maybe it was to be concise. I changed it to `ppm_error'

2022-02-02 07:01 UTC, jorainer requested changes
Perfect! Thanks Andrea! One very last request, please:
- increment the version of the package (the "z" part in "x.y.z"
- add this version also to the NEWS.md and descbribe these changes in the NEWS.

2022-02-02 07:50 UTC, andreavicini commented
I should have done it (also added my ORCID since now I have it, hope it's ok)!

2022-02-02 09:51 UTC, jorainer approved these changes
Perfect! Thanks! I'll merge and push to BioC.

2022-02-02 09:51 UTC, merged