matchMz, CompareMassParam
rformassspectrometry/MetaboAnnotation pull request #64
Opened 2022-03-02 11:07 UTC by andreavicini

Hi, this PR contains a first implementation of the `matchMz, CompareMassParam` that we discussed in issue #56. There are a few things I'm not very sure of and I will try to add specific question on the code.

2022-03-02 11:09 UTC, andreavicini commented on R/matchMz.R
> +         contains = "MzParam",
Is this ok or should I just inherit from `"Param"`? The name might be misleading but actually `"MzParam"` would be ok also for mass matching. We could even inherit from `"Mass2MzParam"` adding only the slot "queryAdducts" (and possibly rename slot "adduct" to "targetAdducts" in "Mass2MzParam"). What do you think would be best?

2022-03-02 11:12 UTC, andreavicini commented on R/matchMz.R
> +              if (nrow(matches[[i]]))
or create separate columns for query and target adducts?

2022-03-02 11:14 UTC, michaelwitting commented on R/matchMz.R
> +              if (nrow(matches[[i]]))
It would be helpful to know which adducts matched.

2022-03-02 11:17 UTC, andreavicini commented on R/matchMz.R
> +          })
The functions with different signatures for `query` and `target` and `param = "CompareMassParam"` are identical to the corresponding ones for `param = "MzParam"`. So initially I was thinking maybe to put in the signature of these functions param equal to the union of  `"CompareMassParam"` and `"MzParam"` classes. But I noticed that even without that everything seem to work. Could it be because `"CompareMassParam"` inherits from “MzParam”? Is this ok or better to specify functions for other signatures?

2022-03-02 11:26 UTC, andreavicini commented on R/matchMz.R
> +              if (nrow(matches[[i]]))
Sorry, I referenced one line above. Information on matched adducts is added in the same way as in PR #58.

2022-03-02 15:04 UTC, jorainer requested changes
Thanks Andrea for implementing! While going through the code I realized (like you did) that there is room to avoid redundancy and code duplication. Maybe we should first discuss some suggested changes also in issue #56 and then adapt this PR.

2022-03-02 15:04 UTC, jorainer commented on R/matchMz.R
> +         contains = "MzParam",
I think it would be good to rename the `adduct` slot in `Mass2MzParam` to `targetAdduct` and also add a `queryAdduct` slot to `Mass2MzParam` (even if we don't use it for now). Then I would rename the `CompareMassParam` class maybe to `Mz2MassParam` (see also discussion issue #56 ) and make that extending `Mass2MzParam`.

I'm actually even wondering if we shouldn't also add a slot `FUN` to that class with default value `@FUN = mass2mz` for `Mass2MzParam` and `@FUN = mz2mass` for `Mz2MassParam` - the user should not have the possibility to set this slot (i.e. it should not be included as a parameter in the `Mass2MzParam` or `Mz2MassParam` functions...

2022-03-02 15:43 UTC, andreavicini commented on R/matchMz.R
> +           queryAdducts = "adductClass",
It should be defined in AllClassUnions.R. It should also allow to pass customized adduct definitions as a `data.frame`

2022-03-04 08:24 UTC, jorainer commented on R/matchMz.R
> +           queryAdducts = "adductClass",
Ah, OK! makes sense!

2022-03-11 07:42 UTC, andreavicini commented on R/matchMz.R
> +                  rbind, bpmapply(seq_along(query), query, FUN = .getMatches,
Was there a reason why for this function we left `bpmapply` instead of a `for` loop like in all the other functions?

2022-03-11 07:45 UTC, andreavicini commented on R/matchMz.R
>            function(query, target, param, BPPARAM = SerialParam()) {
And here, like in all the other function where `bpmapply` is not used maybe `BPPARAM` is not needed

2022-03-11 09:34 UTC, jorainer commented on R/matchMz.R
> +                  rbind, bpmapply(seq_along(query), query, FUN = .getMatches,
Hm, I don't know. `bpmapply` would make only sense if `.getMatches` is slow. Question is also if for loop or simple `lapply`?

2022-03-11 09:35 UTC, jorainer commented on R/matchMz.R
>            function(query, target, param, BPPARAM = SerialParam()) {
yes, you're right.

2022-03-11 09:59 UTC, jorainer requested changes
Quite a comprehensive PR ;) Looks good Andrea, I have some minor change requests but the rest really looks great.

2022-03-11 09:59 UTC, jorainer commented on R/matchMz.R
> +          function(query, target, param, valueColname,
what happens when `valueColname` is not defined? do you have a unit test for that?

2022-03-11 09:59 UTC, jorainer commented on R/matchMz.R
> +                  rbind, bpmapply(seq_along(query), query, FUN = .getMatches,
OK for me to convert to for loop if it simplifies the code (and is not slower).

2022-03-11 09:59 UTC, jorainer commented on R/matchMz.R
> +          function(query, target, param, BPPARAM = SerialParam()) {
remove the `BPPARAM` if you're using a `for` loop.

2022-03-11 09:59 UTC, jorainer commented on R/matchMz.R
> +              target_mz <- data.frame(index = seq_along(target),
This looks identical to `matchMz, numeric, numeric, ValueParam` - so I think you can completely remove this method, since `MzParam` is also inheriting from `ValueParam`.

2022-03-11 09:59 UTC, jorainer commented on R/matchMz.R
> +          function(query, target, param, BPPARAM = SerialParam()) {
drop the `BPPARAM` here.

2022-03-11 09:59 UTC, jorainer commented on R/matchMz.R
> +ValueParam <- function(tolerance = 0, ppm = 5) {
Actually, I think it would also good to export the `ValueParam` function. In the documentation I would maybe then just clarify that `MzParam` is an alias for `ValueParam` that allows to directly compare provided values.

2022-03-11 09:59 UTC, jorainer commented on R/matchMz.R
> +#'     for parameter `adducts`.
I think you'll also need to document the `valueColumn` parameter? Since I assume also the `matchMz, numeric, numeric, ValueParam` is exported.

2022-03-11 10:01 UTC, andreavicini commented on R/matchMz.R
> +                  rbind, bpmapply(seq_along(query), query, FUN = .getMatches,
If I remember correctly the first implementation had `lapply` then we moved to `bpmapply` and finally to the `for` loop (which is used in all the other cases except this one). To be sure maybe I can check which one is best.

2022-03-11 10:21 UTC, andreavicini commented on R/matchMz.R
> +          function(query, target, param, valueColname,
You are right. Actually since you suggested not to export `ValueParam` I thought also `matchMz, ValueParam` wouldn't be used directly by the user but maybe like you said it wouldn't be bad to export it even though maybe it's not very likely that the user wants to match other things than mz and mass. If `valueColname` is not defined I think an error should be thrown (because there's not default value for it) but I could add a condition `if (missing(valueColname)) stop("`ValueParam` has to be provided")` and check this in a unit test.

2022-03-11 10:23 UTC, andreavicini commented on R/matchMz.R
> +              target_mz <- data.frame(index = seq_along(target),
You are right! Thanks!

2022-03-17 07:46 UTC, michaelwitting commented
Yes, we would need a `Mz2MassRtParam` for matching between ion modes and use `rtime` as additional filter. Here two `SummarizedExperiment` can be also the input, one as `query` and one as `target`

2022-03-22 08:56 UTC, andreavicini commented
I have added `matchMz, Mz2MassRtParam` but `SummarizedExperiment` is not yet supported and I would like to ask your opinion on that. If besides `query` we allow also `target` to be `SummarizedExperiment` maybe we should create 3 different classes inheriting from `Matched`. At the moment we have `MatchedSummarizedExperiment` where only `query` is expected to be `SummarizedExperiment` and maybe we should add another 2 for the cases when only `target` is `SummarizedExperiment` or both are. Alternatively since the only thing that changes between these is whether or not the `rowData` is called on `query` and/or `target`, maybe  we could define one function that depending on the type of `query`/`target` returns identity or `rowData` and use only the `Matched` class with that. What do you think would be best?

2022-03-22 09:50 UTC, michaelwitting commented
I would go for the solution using only the `rowData` and have simple `Matched` object as results containing the `rowData` of both, `query` and `target`

2022-03-22 14:48 UTC, andreavicini commented
I thought we wanted to have the slot `@query` of the matched object to contain the object passed via `matchMz` parameter `query` but yes as you said we could also could fill slot `@query` with `rowData(query)`. In that case then we wouldn’t need the `MatchedSummarizedExperiment` class or similar any more

2022-03-22 17:04 UTC, michaelwitting commented
Maybe we can get feedback from @jorainer ? I didn't use it so far with a `SummarizedExperiment`. How would the return data look like when I'm calling `matchedData` is it the complete data with intensities or only everything in `rowData` of `query` and `target`?

2022-03-23 08:11 UTC, andreavicini commented
Calling `matchedData` on a `MatchedSummarizedExperiment` returns by default all columns in `rowData(query)` and `target` (plus variables associated to the matches such as `score`)

2022-03-23 10:57 UTC, michaelwitting commented
Okay. That is fine for me. I wasn't sure about the return of `matchedData`, if it would have returned everything that would have been a lot. I think it makes sense then to have a `MatchSummarizedExperiment`

2022-03-23 15:43 UTC, jorainer commented
Sorry, I'm a little late on the discussion here. I think `@query` or `@target` should always contain the full input object (e.g. the full `SummarizedExperiment`) but, as @andreavicini pointed out, matching is done on `rowData` and hence `rowData` is also presented with the `matchedData` function.

I haven't thought we will need to support also a `target = SummarizedExperiment`, but maybe that's good to have - for completeness.

2022-03-23 15:49 UTC, jorainer commented
Actually, I would prefer to first merge this PR before adding support for `SummarizedExperiment` @andreavicini - otherwise the PR becomes rather lengthy and hard to read.

2022-03-23 16:00 UTC, andreavicini commented
I agree. I too had the impression that this PR maybe is getting rather lenghty.

2022-03-23 16:01 UTC, jorainer approved these changes
I'm OK with this PR. Let's merge and then work separately on the `SummarizedExperiment`.

2022-03-23 16:01 UTC, merged